name: deploy-stage
on:
    push:
        branches:
            - staging
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.SERVER }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localDir: "./"
        remoteDir: "/wp-content/themes/tvlr/"
        options: "--delete --asci"