name: deploy-stage
on:
    push:
        branches:
            - staging
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
        server-dir: /wp-content/themes/tvlr/
        local-dir: ./